apiVersion: v1
kind: Service
metadata:
  name: echo-headless
  namespace: studybuddies
spec:
  clusterIP: None
  selector:
    app: echo
  ports:
    - name: http
      port: 80
      targetPort: 8080
