apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: echo
  namespace: studybuddies
spec:
  replicas: 3
  selector:
    matchLabels:
      app: echo
  serviceName: echo-headless
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - name: echo
        image: hashicorp/http-echo
        args:
          - "-text=Hello from $(POD_NAME)"
          - "-listen=:8080"
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        ports:
        - containerPort: 8080
