### v1 deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: v1-deployment
  namespace: studybuddies
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mycanaryapp
      version: v1
  template:
    metadata:
      labels:
        app: mycanaryapp
        version: v1
    spec:
      containers:
      - name: echo
        image: hashicorp/http-echo
        args:
          - "-text=Greetings from the v1!"
          - "-listen=:8080"
        ports:
          - containerPort: 8080

---
### canary deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-deployment
  namespace: studybuddies
spec:
  replicas: 0
  selector:
    matchLabels:
      app: mycanaryapp
      version: canary  
  template:
    metadata:
      labels:
        app: mycanaryapp
        version: canary
    spec:
      containers:
      - name: echo
        image: hashicorp/http-echo
        args:
          - "-text=Greetings from the canary!"
          - "-listen=:8080"
        ports:
          - containerPort: 8080
