apiVersion: v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: fortune
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: fortune
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - command:
            - curl
            - https://helloacm.com/api/fortune/
            image: curlimages/curl
            name: fortune
            resources: {}
          restartPolicy: OnFailure
  schedule: '*/5 * * * *'
status: {}

