apiVersion: apps/v1
kind: Deployment
metadata:
  name: working-app
  namespace: studybuddies
spec:
  replicas: 1
  selector:
    matchLabels:
      app: working-app
  template:
    metadata:
      labels:
        app: working-app
    spec:
      containers:
        - name: web
          image: python:3.11-slim
          ports:
            - containerPort: 8080
          args: ["python", "-m", "http.server", "8080"]
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: working-service
  namespace: studybuddies
spec:
  selector:
    app: working-app
  ports:
    - port: 80
      targetPort: 8080
