apiVersion: apps/v1
kind: Deployment
metadata:
  name: buggy-app
  namespace: studybuddies
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buggy-app
  template:
    metadata:
      labels:
        app: buggy-app
    spec:
      containers:
        - name: web
          image: busybox
          args:
            - sleep
            - "5"
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5

...
---
apiVersion: v1
kind: Service
metadata:
  name: buggy-service
  namespace: studybuddies
spec:
  selector:
    app: buggy-app
  ports:
    - port: 80
      targetPort: 8080


