apiVersion: apps/v1
kind: Deployment
metadata:
  name: homework1
  namespace: studybuddies
spec:
  replicas: 2
  selector:
    matchLabels:
      app: homework1
  template:
    metadata:
      labels:
        app: homework1
    spec:
      containers:
      - name: echo
        image: hashicorp/http-echo
        args:
          - "-text=Hallöchen from your homework pod!"
          - "-listen=:8080"
        ports:
          - containerPort: 8080

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homework-ingress
  namespace: studybuddies
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: homework.yourcooldomain.com                 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: homework1-service
            port:
              number: 80
---

apiVersion: v1
kind: Service
metadata:
  name: homework1-service
  namespace: studybuddies
spec:
  selector:
    app: homework
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
