### blue deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment
  namespace: studybuddies
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      version: blue
  template:
    metadata:
      labels:
        app: myapp
        version: blue
    spec:
      containers:
      - name: echo
        image: hashicorp/http-echo
        args:
          - "-text=Hallöchen from the BLUE side!"
          - "-listen=:8080"
        ports:
          - containerPort: 8080

---
### green deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment
  namespace: studybuddies
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      version: blue
  template:
    metadata:
      labels:
        app: myapp
        version: blue
    spec:
      containers:
      - name: echo
        image: hashicorp/http-echo
        args:
          - "-text=Hallöchen from the GREEN side!"
          - "-listen=:8080"
        ports:
          - containerPort: 8080
