# Image from which we are starting
FROM python:3.13-slim

# Set working directory
WORKDIR /app

# Copy your script into the container
COPY miaumiau.py .
ENV IFEELLIKEA="FRISBEE"

# Run the script on container start
CMD ["python", "miaumiau.py"]