apiVersion: v1
kind: Service
metadata:
  name: homework2-service
  namespace: studybuddies
spec:
  selector:
    app: homework2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
