apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-coolest-app-in-the-world
spec:
  template:
    spec:
      containers:
      - name: the-coolest-app-in-the-world
        env:
          - name: foo
            value: we-are-in-dev
        envFrom:
          - configMapRef:
              name: app-config
          - secretRef:
              name: credentials