apiVersion: v1
kind: PersistentVolume
metadata:
  name: mycoolpv
spec:
  capacity:
    storage: 2Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data
