apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: evencoolerpvc
  namespace: studybuddies
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Mi
  storageClassName: ""
