apiVersion: v1
kind: Pod
metadata:
  name: mycuteresourcepod
  namespace: studybuddies
spec:
  containers:
  - name: mycuteresourcepod
    image: nginx
    resources:
      requests:
        memory: "100Mi"
        cpu: "200m"
      limits:
        memory: "256Mi"
        cpu: "500m"
