apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: secure-joke
  name: secure-joke
  namespace: studybuddies
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secure-joke
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: secure-joke
    spec:
      containers:
      - name: curl-container
        image: curlimages/curl
        command:
        - curl
        - -s
        - https://icanhazdadjoke.com/
        securityContext:                      # Added security context for the container
          runAsUser: 1000                     # Added security context for the container
          readOnlyRootFilesystem: true        # Added security context for the container
        resources: {}
status: {}
